[package]
name = "oxide"
version = "0.1.0"
authors = ["1aguna <mlusher28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
impl_ops = "0.1.1"